spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: ${POSTGRES_DRIVER:org.postgresql.Driver}
    url: jdbc:postgresql://localhost:5432/addressbook
    username: foo
    password: bar
    # docker run --name postgres_addressbook -e POSTGRES_PASSWORD=bar -e POSTGRES_USER=foo -e POSTGRES_DB=addressbook -p 5432:5432 -d postgres